<div>
    <div class="title">Charcoal Sunsets</div>
    <div class="paragraph">At twilight, the trees silhouetted against a cerulean-diminishing sky project a color green so deep that it would be easy to mistake for black. Relax, and let your eyes adjust for a long while in this silence, whose only timekeepers are the stars and the crickets. Flattened to two dimensions, the structural leafy complexity is heightened, as if having absorbed the energy released by the absence of light spread across their branching multitude in the third dimension; one infinity replaced by another. What zany characters they.</div>
    <hr />
    <div class="paragraph">On several evening walks at Ashley Reservoir, I observed the sun setting behind the wooded hills of the Metacomet Ridge &mdash; each a moment ushering in the closing of another day, as if settling an unpleasant argument with a silence so conciliatory and quieting as to portend an uneasy if tranquil peace.</div>
    <img class="imageHorizontalWidth" src="/assets/images/landscapes/Ashley%20Sunset.1.jpg" title="Sunset, Ashley Reservoir, Number 1" />
    <div class="label">2025 : charcoal on paper : 5 x 7 inches</div>
    <div class="paragraph">To be honest, the corniness of the idea is what appealed to me, what took hold as an idea worth having and doing something with. I felt that to attempt to capture those moments, I must do it head-on and in a manner so counterfactual to the experience itself, that it might just be possible in some abstraction to express. Corniness promised risk, because hasn't this been the same compositional exercise that every high school student has had to endure as unwitting or unwanting practitioners of an hourly art, sandwiched between serious study.</div>
    <img class="imageHorizontalWidth" src="/assets/images/landscapes/Ashley%20Sunset.2.jpg" title="Sunset, Ashley Reservoir, Number 2" />
    <div class="label">2025 : charcoal on paper : 5 x 6.75 inches</div>
    <div class="paragraph">The blanket of evening hues spread across the larger evening sky, so impossibly subtle and so rich and so often given to colorful verse of course demanded a treatment in shades of gray. The charcoal sticks, which I had carried for the better part of 20 years, cooperated: pushing and scratching and rubbing and lifting in erasure, which ironically (magically?) gave rise to the light from some deep carbon tone. The paper starts white (off-white) so that's where the light comes from, naturally; but it only emerges after a considerable application of and negotiation with its exact opposite.</div>
    <img class="imageHorizontalWidth" src="/assets/images/landscapes/Ashley%20Sunset.3.jpg" title="Sunset, Ashley Reservoir, Number 3" />
    <div class="label">2025 : charcoal on paper : 5 x 6.75 inches</div>
    <div class="paragraph">In the first drawing, the sun is absent except in effect. In the other two, the sun is eclipsed by the tree-lined hills. A particularly salient part of that risk I referred to earlier, it was important to me to get right the way in which that event diffused and radiated the spherical concentration of light, as if to be at a loss for words.</div>
    <div class="paragraph">At the time, it was not hard to look directly into, unless one recognized in it a metaphor.</div>
</div>
